name: app_perufest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  intl: ^0.20.2
  provider: ^6.0.0
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  http: ^1.1.0
  image_picker: ^1.0.4
  supabase_flutter: ^2.0.0
  timezone: ^0.10.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  url_launcher: ^6.2.2
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
